trigger:
- master

variables:
  ResourceGroupName: dsclab
  AutomationAccountName: dsclab
  skipComponentGovernanceDetection: true

stages:
- stage: Deploy
  jobs: 
    - deployment: 
      environment: Production
      pool:
        vmImage: 'windows-latest'
      strategy: 
        runOnce:
          deploy:
            steps:
              - checkout: self
              - task: AzurePowerShell@4
                displayName: 'Upload Configuration'
                enabled: false
                inputs:
                  azureSubscription: 'AzureConnect'
                  ScriptType: 'FilePath'
                  ScriptPath: '$(System.DefaultWorkingDirectory)\\Pipeline\\1_UploadConfiguration.ps1'
                  azurePowerShellVersion: 'LatestVersion'
              - task: AzurePowerShell@4
                displayName: 'Compile Configuration'
                enabled: false
                inputs:
                  azureSubscription: 'AzureConnect'
                  ScriptType: 'FilePath'
                  ScriptPath: '$(System.DefaultWorkingDirectory)\\Pipeline\\2_CompileConfiguration.ps1'
                  azurePowerShellVersion: 'LatestVersion'
              - task: AzurePowerShell@4
                displayName: 'Upload Runbook'
                enabled: false
                inputs:
                  azureSubscription: 'AzureConnect'
                  ScriptType: 'FilePath'
                  ScriptPath: '$(System.DefaultWorkingDirectory)\\Pipeline\\3_UploadRunbook.ps1'
                  azurePowerShellVersion: 'LatestVersion'
              - task: AzurePowerShell@4
                displayName: 'Register DSC Nodes'  
                inputs:
                  azureSubscription: 'AzureConnect'
                  ScriptType: 'FilePath'
                  ScriptPath: '$(System.DefaultWorkingDirectory)\\Pipeline\\4_RegisterDSCNode.ps1'
                  azurePowerShellVersion: 'LatestVersion'

