trigger:
- master

variables:
  ResourceGroupName: dsclab
  AutomationAccountName: dsclab
  skipComponentGovernanceDetection: true
  System.Debug: true

stages:
- stage: Deploy
  jobs: 
    - deployment: 
      environment: Production
      pool:
        vmImage: 'windows-latest'
      strategy: 
        runOnce:
          deploy:
            steps:
              - task: AzurePowerShell@4
                inputs:
                  azureSubscription: 'AzureConnect'
                  ScriptType: 'FilePath'
                  ScriptPath: '$(System.DefaultWorkingDirectory)\\Pipeline\\1_UploadConfiguration.ps1'
                  azurePowerShellVersion: 'LatestVersion'

